package: package-lock.json package.json
	npm install

bundle: ./src/scripts/*
	npm run build

exec:
	npm run build-exe

start: 
	npm run start

clean: 
	rm -rf node_modules/*
	rm -rf node_modules/
	rm -rf bin/*
	rm -rf bin/